# docker-compose.yml for Talk to Your PC MCP Server
version: '3.8'

services:
  talk-to-pc-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talk-to-pc-mcp-server
    ports:
      - "8081:8081"
    environment:
      # LLM API Keys - set these in your environment or .env file
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - PORT=8081
      - PYTHONPATH=/app/src
    volumes:
      # Mount for development (optional)
      - ./src:/app/src:ro
      - ./http_server.py:/app/http_server.py:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: talk-to-pc-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro 
    depends_on:
      - talk-to-pc-mcp
    restart: unless-stopped
    networks:
      - mcp-network
    profiles:
      - production

networks:
  mcp-network:
    driver: bridge

volumes:
  ssl_certs:
    driver: local